version: '3.1'

services:

  mariadb:
    image: mariadb:10.5
    container_name: mariadb-service
    networks:
      - gotham-city-network
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - $PWD/Database:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE:  ${DB_DATABASE}
      MYSQL_USER:  ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: phpmyadmin-service
    networks:
      - gotham-city-network
    ports:
      - 8000:80
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb

  batman:
    build:
      context: ./Batman
      dockerfile: Dockerfile
    container_name: batman-service
    networks:
      - gotham-city-network
    ports:
      - "5000:80"
    environment:
      DB_CONNECTION: Server=${DB_HOST};Port=${DB_PORT};Database=${DB_DATABASE};User=${DB_USER};Password=${DB_PASSWORD};
    depends_on:
      - mariadb

  robin:
    build:
      context: ./Robin
      dockerfile: Dockerfile
    container_name: robin-service
    networks:
      - gotham-city-network
    environment:
      DB_CONNECTION: Server=${DB_HOST};Port=${DB_PORT};Database=${DB_DATABASE};User=${DB_USER};Password=${DB_PASSWORD};
    depends_on:
      - mariadb

volumes:
  db-data:

networks:
  gotham-city-network:
    driver: bridge
